-- Script generated by WINDEV on 23/11/2020 22:27:38
-- Tables of InscripcionesSOAP.wda analysis
-- for SQL Server

CREATE DATABASE inscripcionBD_SOA
USE inscripcionBD_SOA

-- Creating the alumno table
CREATE TABLE [alumno] (
    [alumnoID] NUMERIC(19,0)  IDENTITY  PRIMARY KEY ,
    [nombre] VARCHAR(100) ,
    [noControl] VARCHAR(50) ,
    [estatus] CHARACTER(1) );

-- Creating the conceptoPago table
CREATE TABLE [conceptoPago] (
    [conceptoPagoID] NUMERIC(19,0)  IDENTITY  PRIMARY KEY ,
    [descripcion] VARCHAR(100) );

-- Creating the inscripcion table
CREATE TABLE [inscripcion] (
    [inscripcionID] NUMERIC(19,0)  IDENTITY  PRIMARY KEY ,
    [fecha] DATETIME ,
    [referencia] VARCHAR(50) ,
    [PagoID] NUMERIC(19,0)  UNIQUE ,
    [AlumnoID] NUMERIC(19,0)  UNIQUE );

-- Creating the pago table
CREATE TABLE [pago] (
    [pagoID] NUMERIC(19,0)  IDENTITY  PRIMARY KEY ,
    [fechaRealizacion] DATETIME ,
    [monto] INTEGER DEFAULT 0,
    [validado] CHARACTER(1) ,
    [ConceptoPagoID] NUMERIC(19,0) ,
    [fechaValidacion] DATETIME );
CREATE INDEX [WDIDX_pago_ConceptoPagoID] ON [pago] ([ConceptoPagoID]);
-- Integrity constraints
ALTER TABLE [pago] ADD FOREIGN KEY ([ConceptoPagoID]) REFERENCES [conceptoPago] ([conceptoPagoID]);
ALTER TABLE [inscripcion] ADD FOREIGN KEY ([PagoID]) REFERENCES [pago] ([pagoID]);
ALTER TABLE [inscripcion] ADD FOREIGN KEY ([AlumnoID]) REFERENCES [alumno] ([alumnoID]);


/*==============================================================*/
/* CREACION DEL USUARIO QUE TENDRA ACCESO A LA BD                */
/*==============================================================*/

create login inscripcionSOAP
with password='inscripcionSOAP.123',
default_database=inscripcionBD_SOA
go

create user inscripcionSOAP
for login inscripcionSOAP
go

exec sp_addrolemember db_datawriter,inscripcionSOAP
exec sp_addrolemember db_datareader,inscripcionSOAP
go

grant execute on schema::dbo to inscripcionSOAP
go






